### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by bugith** [soulfish/px5deditor#27]
Ola soulfish, here af from linuxmao.org
The installation in my ubuntu 13.04 64bits with unity was ok after I installed the build-essential package (plus the ones you advise).
I had to gksudo gedit /usr/share/applications/px5deditor.desktop to get a specific icon instead of the generic question mark one, this way:
replaced 
Icon=px5deditor
with 
Icon=/usr/share/icons/hicolor/48x48/apps/px5deditor.png

I believe in ubuntu, the launchers are .desktop files located in ~/.local/share/applications
this may be the reason, or a missing path or something to hicolor/NxN/apps/ ? 
I guess it must be borring to deal with all these specifics in various distros.

Thank you for the nice job

**Comment by soulfish** [comment]
Better late than never, I'm fixing this one. ;)

**Comment by soulfish** [comment]
Fixed in version 0.3
