### ISSUE TITLE
Failing to link (with solution)

### ISSUE THREAD

**Issue by giampierosalvi** [soulfish/px5deditor#29]
Hi,
when I build the code, I get the following error:
/usr/bin/ld: CMakeFiles/px5deditor.dir/engine/RtMidi.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
...

Tested on Ubuntu 16.04
cmake version 3.5.1
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

This can be fixed by adding "-pthread" to TARGET_LINK_LIBRARIES in CMakeLists.txt, line 114. The line looks like this:

TARGET_LINK_LIBRARIES( px5deditor ${QT_LIBRARIES} ${ALSA_LIBRARIES} -pthread )

I would have done a pull request if it wasn't so complicated for just a single line of code.

Hope you can incorporate the change.

Thank you for the great software!
Giampiero

**Comment by soulfish** [comment]
Hi @giampierosalvi ! Thanks for reporting this. I've tested your fix for the build issue and will commit ASAP. Thanks.

**Comment by soulfish** [comment]
Fixed in version 0.3
